
DROP TABLE IF EXISTS admin CASCADE ;

CREATE TABLE IF NOT EXISTS admin(
  id SERIAL NOT NULL PRIMARY KEY ,
  email VARCHAR (255) UNIQUE NOT NULL ,
  password VARCHAR (255) NOT NULL
);

INSERT INTO admin (email, password) VALUES ('exist@e.ru', '$2a$10$rXn4xiRPY45wJVi39KAm.eKElUDcBQI4b58sqiEjrTXaTFrRn5nOW');
